horizon:
  start_date: 2025-11-01
  end_date: 2025-11-30

rest_rules:
  min_between_shifts_h: 11
  post_night_rest_h: 48
  rest11_penalty_weight: 1.0
  weekly_rest_penalty_weight: 1.0

preassignments:
  change_penalty_weight: 5.0

fairness:
  night_weight: 1.0
  weekend_weight: 1.0

defaults:
  allowed_roles: ["infermiere", "oss", "caposala"]
  departments: ["ortopedia", "cardiologia", "degenza", "pneumologia", "malattie infettive", "pronto_soccorso", "ambulatorio"]
  weekly_rest_min_days: 1
  biweekly_rest_min_days: 2
  contract_hours_by_role_h:
    infermiere: 168
    oss: 168
    caposala: 150
  absences:
    count_as_worked_hours: true
    full_day_hours_by_role_h:
      INFERMIERE: 7.5
      OSS: 7.5
      CAPOSALA: 7.0
    fallback_contract_daily_avg_h: 7.5
  rest11h:
    max_monthly_exceptions: 0
    max_consecutive_exceptions: 0
  overstaffing:
    enabled: true
    group_cap_default: 0
  balance:
    max_balance_delta_month_h: 0
    due_hours_penalty_weight: 1.0
  night:
    max_consecutive_nights: 3
    can_work_night: true
    max_per_week: 2
    max_per_month: 8
    extra_consecutive_penalty_weight: 1.0
    single_night_recovery_penalty_weight: 1.0
    night_to_day_penalty_weight: 1.0
  fairness:
    night_weight: 1.0
    weekend_weight: 1.0

roles:
  infermiere:
    can_work_night: true
    night:
      max_per_week: 2
      max_per_month: 8
  oss:
    can_work_night: true
  caposala:
    can_work_night: true

shift_types:
  night_codes: ["N"]

cross:
  max_shifts_month: 6
  penalty_weight: 1.5

locks:
  allow_cross_reparto: true
