horizon:
  start_date: 2025-11-01
  end_date: 2025-11-30

rest_rules:
  min_between_shifts_h: 11
  post_night_rest_h: 48
  weekly_rest_min_h: 24

defaults:
  allowed_roles: ["infermiere", "oss", "caposala"]
  departments: ["ortopedia", "cardiologia", "degenza", "pneumologia", "malattie infettive"]
  contract_hours_by_role_h:
    infermiere: 168
    oss: 168
    caposala: 168
  night:
    can_work_night: true
    max_per_week: 2
    max_per_month: 8
roles:
  infermiere:
    can_work_night: true
    night:
      max_per_week: 2
      max_per_month: 8
  oss:
    can_work_night: true
  caposala:
    can_work_night: false
shift_types:
  night_codes: ["N"]
payroll:
  absence_hours_h: 6
  fulltime_hours_mensili_default: 165
  fulltime_hours_mensili_by_role:
    caposala: 150
cross:
  max_shifts_week: 2
  max_shifts_month: 6
  penalty_weight: 1.5
preassignments:
  allow_cross_reparto: true
